# Source for mac/Localization/*.lproj/Localizable.strings. Run: python3 strings.py
# Each row: key, English (title case per Apple's HIG), Simplified Chinese, Spanish, Hindi.
ROWS = [
("preset.inOneHour","In 1 Hour","1 小时后","En 1 hora","1 घंटे में"),
("preset.thisMorning","This Morning","今天上午","Esta mañana","आज सुबह"),
("preset.thisEvening","This Evening","今天晚上","Esta noche","आज शाम"),
("preset.tomorrowMorning","Tomorrow Morning","明天上午","Mañana por la mañana","कल सुबह"),
("preset.nextWeek","Next Week","下周","La próxima semana","अगले सप्ताह"),
("panel.pick","Pick a Date & Time…","选择日期和时间…","Elegir fecha y hora…","तारीख और समय चुनें…"),
("panel.pickTitle","Pick a Date & Time","选择日期和时间","Elegir fecha y hora","तारीख और समय चुनें"),
("panel.placeholder","Type a time, like 7pm or tomorrow 9","输入时间，例如 7pm 或 tomorrow 9","Escribe una hora, como 7pm o tomorrow 9","समय लिखें, जैसे 7pm या tomorrow 9"),
("panel.inputName","Time to bring the window back","窗口回来的时间","Hora a la que vuelve la ventana","विंडो वापस लाने का समय"),
("panel.close","Close","关闭","Cerrar","बंद करें"),
("panel.back","Back","返回","Atrás","वापस"),
("panel.date","Date","日期","Fecha","तारीख"),
("panel.time","Time","时间","Hora","समय"),
("panel.snooze","Snooze","延后","Posponer","स्नूज़ करें"),
("panel.changeSubtitle","Now coming back %@","当前回来时间：%@","Ahora vuelve %@","अभी वापसी: %@"),
("parse.past","That time has already passed","这个时间已经过去了","Esa hora ya pasó","यह समय बीत चुका है"),
("parse.tooFar","Pick a time within the next year","请选择一年之内的时间","Elige una hora dentro del próximo año","अगले एक साल के भीतर का समय चुनें"),
("parse.unrecognized","Try 7pm, tomorrow 9, or 2h","试试 7pm、tomorrow 9 或 2h","Prueba 7pm, tomorrow 9 o 2h","7pm, tomorrow 9 या 2h लिखकर देखें"),
("refusal.fullScreenTitle","Can't Snooze a Full-Screen Window","无法延后全屏窗口","No se puede posponer una ventana a pantalla completa","फ़ुल-स्क्रीन विंडो स्नूज़ नहीं हो सकती"),
("refusal.fullScreen","Exit full screen first, then press %@ again.","请先退出全屏，然后再次按 %@。","Sal primero de la pantalla completa y vuelve a pulsar %@.","पहले फ़ुल स्क्रीन से बाहर निकलें, फिर %@ दोबारा दबाएँ।"),
("refusal.notStandardTitle","Can't Snooze This Window","无法延后此窗口","No se puede posponer esta ventana","यह विंडो स्नूज़ नहीं हो सकती"),
("refusal.notStandard","Only regular app windows can be snoozed, not panels or dialogs.","只能延后普通的应用窗口，面板和对话框不行。","Solo se pueden posponer ventanas normales de apps, no paneles ni cuadros de diálogo.","सिर्फ़ सामान्य ऐप विंडो स्नूज़ की जा सकती हैं, पैनल या डायलॉग नहीं।"),
("refusal.noWindowTitle","Nothing to Snooze","没有可延后的窗口","Nada que posponer","स्नूज़ करने के लिए कुछ नहीं"),
("refusal.noWindow","Click the window you want to snooze, then press %@.","先点按要延后的窗口，然后按 %@。","Haz clic en la ventana que quieres posponer y pulsa %@.","जिस विंडो को स्नूज़ करना है उस पर क्लिक करें, फिर %@ दबाएँ।"),
("failure.storage","The snooze couldn't be saved, so the window was left open.","无法保存此次延后，窗口保持打开。","No se pudo guardar, así que la ventana sigue abierta.","स्नूज़ सहेजा नहीं जा सका, इसलिए विंडो खुली छोड़ दी गई।"),
("failure.gone","That window has closed.","该窗口已关闭。","Esa ventana se ha cerrado.","वह विंडो बंद हो चुकी है।"),
("failure.refused","The app put this window straight back, so it can't be snoozed.","该应用立即把窗口显示了回来，因此无法延后。","La app volvió a mostrar la ventana enseguida, así que no se puede posponer.","ऐप ने विंडो तुरंत वापस दिखा दी, इसलिए इसे स्नूज़ नहीं किया जा सकता।"),
("when.today","Today at %@","今天 %@","Hoy a las %@","आज %@"),
("when.tomorrow","Tomorrow at %@","明天 %@","Mañana a las %@","कल %@"),
("when.day","%1$@ at %2$@","%1$@ %2$@","%1$@ a las %2$@","%1$@ %2$@"),
("menu.snoozeTarget","Snooze “%@”…","延后“%@”…","Posponer «%@»…","“%@” स्नूज़ करें…"),
("menu.snoozeAny","Snooze a Window…","延后窗口…","Posponer una ventana…","कोई विंडो स्नूज़ करें…"),
("menu.empty","No Snoozed Windows","没有已延后的窗口","No hay ventanas pospuestas","कोई विंडो स्नूज़ नहीं है"),
("menu.snoozed","Snoozed","已延后","Pospuestas","स्नूज़ की गई"),
("menu.closed","Window closed · reminder %@","窗口已关闭 · 提醒时间 %@","Ventana cerrada · aviso %@","विंडो बंद हो गई · रिमाइंडर %@"),
("menu.bringBack","Bring Back Now","立即恢复","Recuperar ahora","अभी वापस लाएँ"),
("menu.changeTime","Change Time…","更改时间…","Cambiar hora…","समय बदलें…"),
("menu.bringBackAll","Bring Back All","全部恢复","Recuperar todas","सभी वापस लाएँ"),
("menu.settings","Settings…","设置…","Ajustes…","सेटिंग्ज़…"),
("menu.checkUpdates","Check for Updates…","检查更新…","Buscar actualizaciones…","अपडेट के लिए जाँचें…"),
("menu.quit","Quit Bring Later","退出 Bring Later","Salir de Bring Later","Bring Later बंद करें"),
("menu.tooltip","Bring Later – %@ snoozed","Bring Later – %@ 个已延后","Bring Later – %@ pospuestas","Bring Later – %@ स्नूज़ की गई"),
("notify.show","Show","显示","Mostrar","दिखाएँ"),
("notify.snoozeHour","Snooze 1 Hour","延后 1 小时","Posponer 1 hora","1 घंटे के लिए स्नूज़ करें"),
("notify.snoozedAt","%1$@ · snoozed at %2$@","%1$@ · 延后于 %2$@","%1$@ · pospuesta a las %2$@","%1$@ · %2$@ पर स्नूज़ की गई"),
("notify.manyBack","%@ windows are back","%@ 个窗口已恢复","Han vuelto %@ ventanas","%@ विंडो वापस आ गईं"),
("notify.two","%1$@ and %2$@","%1$@ 和 %2$@","%1$@ y %2$@","%1$@ और %2$@"),
("notify.more","%1$@, %2$@ and %3$@ more","%1$@、%2$@ 以及另外 %3$@ 个","%1$@, %2$@ y %3$@ más","%1$@, %2$@ और %3$@ अन्य"),
("notify.closed","The %@ window was closed while it was snoozed.","%@ 窗口在延后期间被关闭了。","La ventana de %@ se cerró mientras estaba pospuesta.","स्नूज़ के दौरान %@ की विंडो बंद कर दी गई।"),
("notify.shortcutTakenTitle","Shortcut Unavailable","快捷键不可用","Atajo no disponible","शॉर्टकट उपलब्ध नहीं"),
("notify.shortcutTakenBody","Another app is using %@. Choose a different shortcut in Settings.","%@ 已被其他应用占用。请在设置中选择其他快捷键。","Otra app usa %@. Elige otro atajo en Ajustes.","%@ का इस्तेमाल कोई दूसरा ऐप कर रहा है। सेटिंग्ज़ में कोई दूसरा शॉर्टकट चुनें।"),
("notify.againFailed","Couldn't Snooze It Again","无法再次延后","No se pudo volver a posponer","दोबारा स्नूज़ नहीं हो सका"),
("settings.windowTitle","Bring Later Settings","Bring Later 设置","Ajustes de Bring Later","Bring Later सेटिंग्ज़"),
("settings.snoozing","Snoozing","延后","Posponer","स्नूज़"),
("settings.shortcut","Keyboard Shortcut","键盘快捷键","Atajo de teclado","कीबोर्ड शॉर्टकट"),
("settings.shortcutHint","Opens the snooze panel for the window you're using.","为当前使用的窗口打开延后面板。","Abre el panel para posponer la ventana que estás usando.","जिस विंडो का आप इस्तेमाल कर रहे हैं, उसके लिए स्नूज़ पैनल खोलता है।"),
("settings.shortcutRecord","Press a Shortcut","请按快捷键","Pulsa un atajo","शॉर्टकट दबाएँ"),
("settings.shortcutRecording","Recording. Press the new shortcut.","正在录制，请按下新的快捷键。","Grabando. Pulsa el nuevo atajo.","रिकॉर्ड हो रहा है। नया शॉर्टकट दबाएँ।"),
("settings.shortcutLabel","Keyboard shortcut %@. Click to change.","键盘快捷键 %@，点按以更改。","Atajo de teclado %@. Haz clic para cambiarlo.","कीबोर्ड शॉर्टकट %@। बदलने के लिए क्लिक करें।"),
("settings.shortcutInvalid","Use ⌘ or ⌃ together with another key.","请将 ⌘ 或 ⌃ 与另一个键组合使用。","Usa ⌘ o ⌃ junto con otra tecla.","⌘ या ⌃ को किसी दूसरी की के साथ इस्तेमाल करें।"),
("settings.shortcutTaken","Another app is already using %@. Try a different one.","%@ 已被其他应用占用。请换一个。","Otra app ya usa %@. Prueba con otro.","%@ का इस्तेमाल कोई दूसरा ऐप कर रहा है। कोई दूसरा आज़माएँ।"),
("settings.evening","This Evening","今天晚上","Esta noche","आज शाम"),
("settings.eveningHint","What “this evening” and “tonight” mean.","“今天晚上”和 tonight 表示的时间。","Lo que significan «esta noche» y tonight.","“आज शाम” और tonight का समय।"),
("settings.morning","Morning","上午","Por la mañana","सुबह"),
("settings.morningHint","Used by “tomorrow morning”, “next week” and dates without a time.","“明天上午”、“下周”以及未写时间的日期使用此时间。","Se usa en «mañana por la mañana», «la próxima semana» y fechas sin hora.","“कल सुबह”, “अगले सप्ताह” और बिना समय वाली तारीखों के लिए।"),
("settings.return","When a Window Comes Back","窗口回来时","Cuando una ventana vuelve","जब कोई विंडो वापस आए"),
("settings.returnHint","A notification tells you either way.","两种方式都会发送通知。","En ambos casos recibes una notificación.","दोनों ही स्थितियों में आपको सूचना मिलेगी।"),
("settings.returnQuiet","Show It Without Switching to It","直接显示，不切换过去","Mostrarla sin cambiar a ella","उस पर स्विच किए बिना दिखाएँ"),
("settings.returnFront","Bring It to the Front","切换到前台","Traerla al frente","सबसे आगे लाएँ"),
("settings.general","General","通用","General","सामान्य"),
("settings.launchAtLogin","Launch at Login","登录时打开","Abrir al iniciar sesión","लॉग इन पर खोलें"),
("settings.launchHint","Bring Later has to be running to bring windows back.","Bring Later 需要保持运行才能恢复窗口。","Bring Later tiene que estar abierta para recuperar las ventanas.","विंडो वापस लाने के लिए Bring Later का चलते रहना ज़रूरी है।"),
("settings.accessibility","Accessibility","辅助功能","Accesibilidad","ऐक्सेसिबिलिटी"),
("settings.accessibilityHint","Needed to hide and restore other apps' windows.","用于隐藏和恢复其他应用的窗口。","Necesaria para ocultar y recuperar ventanas de otras apps.","दूसरे ऐप्स की विंडो छिपाने और वापस लाने के लिए ज़रूरी।"),
("settings.allowed","Allowed","已允许","Permitido","अनुमति है"),
("settings.openSystemSettings","Open System Settings","打开系统设置","Abrir Ajustes del Sistema","सिस्टम सेटिंग्ज़ खोलें"),
("settings.about","About","关于","Acerca de","परिचय"),
("settings.version","Version","版本","Versión","संस्करण"),
("settings.updates","Updates","更新","Actualizaciones","अपडेट"),
("settings.download","Download","下载","Descargar","डाउनलोड करें"),
("settings.checkUpdates","Check for Updates","检查更新","Buscar actualizaciones","अपडेट के लिए जाँचें"),
("settings.source","Source Code","源代码","Código fuente","सोर्स कोड"),
("settings.report","Report a Problem","报告问题","Informar de un problema","समस्या बताएँ"),
("settings.updatesIdle","Checks GitHub for a newer release when you ask. Nothing is sent automatically.","仅在你点按时检查 GitHub 上的新版本，不会自动发送任何数据。","Busca una versión nueva en GitHub solo cuando lo pides. No se envía nada automáticamente.","आपके कहने पर ही GitHub पर नया संस्करण जाँचता है। अपने-आप कुछ नहीं भेजा जाता।"),
("settings.updatesChecking","Checking…","正在检查…","Buscando…","जाँच हो रही है…"),
("settings.updatesCurrent","You have the latest version.","已是最新版本。","Tienes la última versión.","आपके पास नवीनतम संस्करण है।"),
("settings.updatesAvailable","Version %@ is available.","有新版本 %@ 可用。","La versión %@ está disponible.","संस्करण %@ उपलब्ध है।"),
("settings.updatesFailed","Couldn't reach GitHub. Try again later.","无法连接 GitHub，请稍后重试。","No se pudo conectar con GitHub. Inténtalo más tarde.","GitHub से कनेक्ट नहीं हो सका। बाद में फिर कोशिश करें।"),
("access.title","Allow Accessibility Access","允许辅助功能访问","Permitir el acceso de accesibilidad","ऐक्सेसिबिलिटी की अनुमति दें"),
("access.titleAgain","Turn Accessibility Access Back On","重新开启辅助功能访问","Vuelve a activar el acceso de accesibilidad","ऐक्सेसिबिलिटी की अनुमति फिर से चालू करें"),
("access.body","Bring Later uses Accessibility access to hide and restore other apps' windows. It reads window titles so you can tell them apart, and nothing else.","Bring Later 使用辅助功能来隐藏和恢复其他应用的窗口。它只读取窗口标题以便区分窗口，不读取其他内容。","Bring Later usa el acceso de accesibilidad para ocultar y recuperar ventanas de otras apps. Solo lee los títulos de las ventanas para distinguirlas, nada más.","Bring Later दूसरे ऐप्स की विंडो छिपाने और वापस लाने के लिए ऐक्सेसिबिलिटी का इस्तेमाल करता है। यह सिर्फ़ विंडो के शीर्षक पढ़ता है ताकि आप उन्हें पहचान सकें, और कुछ नहीं।"),
("access.bodyAgain","macOS turns off Accessibility access when Bring Later is updated. Turn it on again to keep snoozing windows.","Bring Later 更新后，macOS 会关闭它的辅助功能访问。请重新开启，以便继续延后窗口。","macOS desactiva el acceso de accesibilidad cuando se actualiza Bring Later. Vuelve a activarlo para seguir posponiendo ventanas.","Bring Later अपडेट होने पर macOS उसकी ऐक्सेसिबिलिटी अनुमति बंद कर देता है। विंडो स्नूज़ करते रहने के लिए इसे फिर से चालू करें।"),
("access.steps","In System Settings, turn on Bring Later under Privacy & Security › Accessibility. If it's already on, remove it with the minus button and add it again.","在“系统设置”中，前往“隐私与安全性” › “辅助功能”并打开 Bring Later。如果它已经打开，请用减号按钮移除后再重新添加。","En Ajustes del Sistema, activa Bring Later en Privacidad y seguridad › Accesibilidad. Si ya está activada, elimínala con el botón de menos y vuelve a añadirla.","सिस्टम सेटिंग्ज़ में, गोपनीयता और सुरक्षा › ऐक्सेसिबिलिटी में जाकर Bring Later चालू करें। अगर यह पहले से चालू है, तो माइनस बटन से हटाकर फिर से जोड़ें।"),
("access.waiting","Waiting for access…","正在等待授权…","Esperando el acceso…","अनुमति का इंतज़ार है…"),
]

LANGUAGES = ["en", "zh-Hans", "es", "hi"]

if __name__ == "__main__":
    import os
    keys = [r[0] for r in ROWS]
    assert len(keys) == len(set(keys)), "duplicate key"
    for column, language in enumerate(LANGUAGES, start=1):
        os.makedirs(f"{language}.lproj", exist_ok=True)
        with open(f"{language}.lproj/Localizable.strings", "w", encoding="utf-8") as f:
            f.write("/* Generated from mac/Localization/strings.py. Edit that file, not this one. */\n\n")
            for row in ROWS:
                value = row[column].replace("\\", "\\\\").replace('"', '\\"')
                f.write(f'"{row[0]}" = "{value}";\n')
    print(f"{len(ROWS)} strings in {len(LANGUAGES)} languages")
